name: Node - hardhat test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hardhatTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node v18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: go to service directory
      run: cd service && npx hardhat test
    - name: show working directory
      run: pwd
    - name: test with hardhat
      run: npx hardhat test
